set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
setw -g mouse on

set -g @catppuccin_flavor 'frappe'

set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_connect_separator "no"

set -g @plugin 'catppuccin/tmux#latest'
set -g @plugin 'tmux-plugins/tpm'

run '~/.config/tmux/plugins/tpm/tpm'

set -g status-position top

set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_directory}"
